add functions for proxy in terminal

diff --git a/src/zshrc b/src/zshrc
--- a/src/zshrc
+++ b/src/zshrc
@@ -113,3 +113,36 @@ alias caddy_default='caddy -conf ~/.Caddyfile'
 # for Emacs
 alias emacspd='ps aux | grep \\'Emacs --daemon\\''
 alias emacspc='ps aux | grep emacs'
+
+# function for proxy https and http request in terminal
+# you should install privoxy first:
+#   brew install privoxy
+# more info: http://www.cashqian.net/blog/001486989831982332565298e4942a2bb8f56b08f9d2475000
+function proxy_status() {
+    garbage=`ps aux |  grep -v 'grep' | grep 'privoxy'`
+    if test $? -eq 1 ; then
+        echo -e "proxy is off."
+    else
+        echo -e "proxy is on."
+    fi
+}
+
+function proxy_off(){
+    unset http_proxy
+    unset https_proxy
+    garbage=`ps aux |  grep -v 'grep' | grep 'privoxy'`
+    if  test $? -eq 0 ; then
+        privoxy_pid=`ps aux | grep 'privoxy' | grep -v 'grep' | awk '{print $2}'`
+        kill -9 $privoxy_pid || echo -e "privoxy off failed!"
+    fi
+}
+
+function proxy_on() {
+    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
+    export http_proxy="http://127.0.0.1:8118"
+    export https_proxy=$http_proxy
+    garbage=`ps aux |  grep -v 'grep' | grep 'privoxy'`
+    if  test $? -eq 1 ; then
+        privoxy /usr/local/etc/privoxy/config
+    fi
+}
